//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зоомагазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsSet
    {
        public int Id { get; set; }
        public int IdProvider { get; set; }
        public string NameProduct { get; set; }
        public int MkProduct { get; set; }
        public string NumberProduct { get; set; }
        public string Date { get; set; }
    
        public virtual ProvidersSet ProvidersSet { get; set; }
    }
}
