//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зоомагазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProvidersSet()
        {
            this.CustomsSet = new HashSet<CustomsSet>();
            this.StoragSet = new HashSet<StoragSet>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_Home { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomsSet> CustomsSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoragSet> StoragSet { get; set; }
    }
}
