//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зоомагазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoragSet
    {
        public int Id { get; set; }
        public int IdProvider { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Mk { get; set; }
        public int Number { get; set; }
        public decimal Price { get; set; }
    
        public virtual ProvidersSet ProvidersSet { get; set; }
    }
}
